version: '3'
services:
  dbpostgresql:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: streamworx_assignment
    networks:
      - mynetwork
    ports:
      - "5432:5432"
    volumes:
      - ./assignment-dump.sql:/docker-entrypoint-initdb.d/assignment-dump.sql

  api1:
    build:
      context: ./demo_assignment api1
    container_name: api1-container
    ports:
      - "8081:8081"
    depends_on:
      - dbpostgresql
    networks:
      - mynetwork

  api2:
    build:
      context: ./demo_assignment_api2
    container_name: api2-container
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
    networks:
      - mynetwork

  cache:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: redis-server
    networks:
      - mynetwork
networks:
  mynetwork: